"""Fixed ENUM

Revision ID: ac4223238677
Revises: 082dad83bc8e
Create Date: 2025-12-26 20:38:22.687072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac4223238677'
down_revision: Union[str, Sequence[str], None] = '082dad83bc8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'subscription_level',
               existing_type=postgresql.ENUM('base', 'advanced', name='subscriptionlevel'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'subscription_level',
               existing_type=postgresql.ENUM('base', 'advanced', name='subscriptionlevel'),
               nullable=True)
    # ### end Alembic commands ###
