"""Added last_ip and expires_at

Revision ID: dea80df94b80
Revises: f8b94b4560cb
Create Date: 2025-12-25 18:44:44.777633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dea80df94b80'
down_revision: Union[str, Sequence[str], None] = 'f8b94b4560cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_ip', postgresql.INET(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_ip')
    op.drop_column('users', 'expires_at')
    # ### end Alembic commands ###
